### ISSUE TITLE
[Bug]: Blank page when refresh last transactions

### ISSUE THREAD

**Issue by Piit3r** [archethic-foundation/archethic_wallet#40] opened 2022-01-23 16:18 UTC
### What happened?

Obtained a blank page when i clicked "Refresh last transactions", and there is a new transaction.

Steps to reproduce :
1. connect to wallet page
2. transfer uco to this address
3. click the refresh transactions button
=> blank page

Have to F5 the page to get the wallet back.

Tested on browser Chrome.

### What is expected ?

Expected to refresh the last transactions.

**Comment by Piit3r** [comment] 2022-01-23 16:31
Error found in console

`NoSuchMethodError: method not found: 'ass' on null
main.dart.js?v=20220118182300:27435     at CJ.jO (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:31097:20)
main.dart.js?v=20220118182300:27435     at CJ.gag (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:31198:17)
main.dart.js?v=20220118182300:27435     at i_.lC (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:29531:24)
main.dart.js?v=20220118182300:27435     at Wn.kO (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30781:3)
main.dart.js?v=20220118182300:27435     at VV.kQ (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30659:28)
main.dart.js?v=20220118182300:27435     at VV.kO (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30753:6)
main.dart.js?v=20220118182300:27435     at VV.kQ (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30659:28)
main.dart.js?v=20220118182300:27435     at VV.kO (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30753:6)
main.dart.js?v=20220118182300:27435     at OJ.kQ (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30659:28)
main.dart.js?v=20220118182300:27435     at OJ.kO (https://reddwarf03.github.io/archethic_web/main.dart.js?v=20220118182300:30692:6)`

**Comment by redDwarf03** [comment] 2022-01-23 17:35
thanks for the report. I will check this.

**Comment by redDwarf03** [comment] 2022-01-23 22:51
that's a regression since flutter 2.8
a fix will be deploy with flutter 2.10 (see https://github.com/flutter/flutter/issues/95635)
sorry but I can't do anything... just wait for the fix
I let the issue open until it's resolved.

**Comment by redDwarf03** [comment] 2022-02-04 07:25
resolved with flutter 2.10

**Closed by redDwarf03** 2022-02-04 07:25 UTC
Labels: bug, standby
